### ISSUE TITLE
Latest version not available on npm repositories

### ISSUE THREAD

**Issue by noherczeg** [bsalex/angular-loading-overlay-spinjs#2]
Could you please make a relase to NPM repos as well please?

**Comment by AlexZeitler** [comment]
@bsalex Can you please push 1.0.1 to npm as 1.0.0 breaks our build. Thanks!

**Comment by bsalex** [comment]
Done. 
Thank you for reporting the issue.

**Comment by AlexZeitler** [comment]
Thanks, that's much appreciated 👍🏻
